version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build-deploy:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
jobs:
  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1c:3c:26:c1:78:e6:63:8c:cd:56:83:40:bf:f1:d8:d9"
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan 160.153.129.30 >> ~/.ssh/known_hosts
      - run:
          name: Server Deploy
          command: scp -r public/*  ets5cio5mb9p@160.153.129.30:public_html/wp_content/theme/YHMA_theme